spring:
  datasource:
    url: jdbc:mysql://localhost:3306/master_proj_product_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 66666666
  jpa:
    hibernate:
      ddl-auto: update