spring:
  application:
    name: order-service


  datasource:
    url: jdbc:mysql://localhost:3306/master_proj_order_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 66666666
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest








server:
  port: 8080

