spring:
  application:
    name: product-service


  datasource:
    url: jdbc:mysql://localhost:3306/master_proj_product_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 66666666
  jpa:
    hibernate:
      ddl-auto: update


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8081